<div class="container-fluid">
    <div class="row page-title-row">
        <div class="col-md-6">
            <h3>Pages <small>&raquo; Listing</small></h3>
        </div>
        <div class="col-md-6 text-right">
            <a href="#" class="btn btn-success btn-md">
                <i class="fa fa-plus-circle"></i> New Post
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">

            <table id="posts-table" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Subtitle</th>
                    <th>Published</th>
                    <th data-sortable="false">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td data-order="#">&nbsp;</td>
                    <td>
                        <a href="#"
                           class="btn btn-xs btn-info">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                        <a href="#"
                           class="btn btn-xs btn-warning">
                            <i class="fa fa-eye"></i> View
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>