<div class="container-fluid">
    <div class="row page-title-row">
        <div class="col-md-6">
            <h3>Blog Posts <small>&raquo; Listing</small></h3>
        </div>
        <div class="col-md-6 text-right">
            <a href="<?php echo $this->url('blog', array('action'=>'add'));?>" class="btn btn-success btn-md">
                <i class="fa fa-plus-circle"></i> New Post
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">

            <table id="posts-table" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Subtitle</th>
                    <th>Published</th>
                    <th class="text-center" data-sortable="false">Actions</th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->paginator as $blog) : ?>
                    <tr>
                    <td><?php echo $this->escapeHtml($blog->title);?></td>
                    <td><?php echo $blog->title;?></td>
                    <td data-order="<?php echo $blog->title;?>"><?php echo $blog->title;?></td>
                    <td class="text-center">
                        <a href="<?php echo $this->url('admin_blog',
                            array('action'=>'edit', 'id' => $blog->id));?>"
                           class="btn btn-xs btn-info">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                        <a href="<?php echo $this->url('blog',
                            array('action'=>'view', 'id' => $blog->id));?>"
                           class="btn btn-xs btn-warning" target="_blank">
                            <i class="fa fa-eye"></i> View
                        </a>
                        <a href="<?php echo $this->url('admin_blog',
                            array('action'=>'delete', 'id' => $blog->id));?>"
                           class="btn btn-xs btn-danger">
                            <i class="fa fa-eye"></i> Delete
                        </a>
                    </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

</div>

<?php
// add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'admin_blog'
    )
);
?>