<?php
// module/Album/view/blog/blog/index.phtml:

$title = 'My blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div id="blog">
<?php foreach ($this->paginator as $blog) : ?>
    <h2><a href="<?php echo $this->url('blog', array('action'=>'view'));?>/<?php echo $blog->id; ?>"><?php echo $this->escapeHtml($blog->title);?></a></h2>
    <?php echo $this->escapeHtml($blog->body);?>
<?php endforeach; ?>
</div>

<?php
// add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'blog'
    )
);
?>