<?php
// module/Album/view/blog/blog/index.phtml:

$title = 'My blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if ($this->isAllowed( 'hidden_object', 'admin' )) { ?>
<p>
    <a href="<?php echo $this->url('blog', array('action'=>'add'));?>">Add new blog</a>
</p>
<?php } ?>
<div id="blog">
<?php foreach ($blogs as $blog) : ?>
    <h2><a href="<?php echo $this->url('blog', array('action'=>'view'));?>/<?php echo $blog->id; ?>"><?php echo $this->escapeHtml($blog->title);?></a></h2>
    <?php echo $this->escapeHtml($blog->body);?>
    <?php if ($this->isAllowed( 'hidden_object', 'admin' )) { ?>
    <div class="blog_actions">
    <a href="<?php echo $this->url('blog',
        array('action'=>'edit', 'id' => $blog->id));?>">Edit</a>
    <a href="<?php echo $this->url('blog',
        array('action'=>'delete', 'id' => $blog->id));?>">Delete</a>
    </div>
    <?php } ?>
<?php endforeach; ?>
</div>

<ul>
</ul>