<div class="page-header">
    <h1><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h1>
</div>
<?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<div style="width: 330px;" class="form-group">
<dl class="zend_form">
    <?php echo $this->formElementErrors($form->get('identity')); ?>
    <dd><?php echo $this->formInput($form->get('identity')); ?></dd>

    <dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('credential')->setAttribute('class', 'form-control')) . $this->formElementErrors($form->get('credential'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('newCredential')->setAttribute('class', 'form-control')) . $this->formElementErrors($form->get('newCredential'));
        ?></dd>

    <dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('newCredentialVerify')->setAttribute('class', 'form-control')) . $this->formElementErrors($form->get('newCredentialVerify'));
        ?></dd>

    <dd><?php
        //echo $this->formInput($form->get('csrf'));
        echo '<br/>';
        echo $this->formInput($form->get('submit')->setAttribute('class', 'btn btn-success'));
        ?></dd>

</dl>
</div>

<?php echo $this->form()->closeTag(); ?>
